all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        tk:
          archlinux:
          archarm:

        archlinux:
          children:
            arch:
              hosts:
                192.168.30.30:
                192.168.30.3:
                192.168.30.16:
                192.168.30.90:
                192.168.30.91:
                192.168.30.92:
            archarm:
              hosts:

        lxc:
          hosts:
            192.168.30.30:
            192.168.30.3:
            192.168.30.16:

        vm:
          hosts:
            192.168.30.90:
            192.168.30.91:
            192.168.30.92:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
              hosts:
                192.168.30.92:
            kubernetes_master:
              hosts:
                192.168.30.90:
                192.168.30.91:

        bastion:
          hosts:
            192.168.30.30:

        docker:
          hosts:

        worker:
          hosts:
            192.168.30.16:

        grafana:
          hosts:
            192.168.30.20:

        jenkins:
          hosts:
            192.168.30.21:

        dns:
          hosts:
            192.168.30.3:

        proxmox:
          hosts:
            192.168.30.55:

