all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        tk-pv:
          archlinux:
          archarm:

        archlinux:
          children:
            arch:
              hosts:
                192.168.20.17:
                192.168.20.18:
                192.168.20.60:
            archarm:
              hosts:

        lxc:
          hosts:
            192.168.20.18:
            192.168.20.60:

        worker:
          hosts:
            192.168.20.18:

        bastion:
          hosts:
            192.168.20.60:

        llm:
          hosts:
            192.168.20.17:

        webui:
          hosts:
            192.168.20.17:

        agent:
          hosts:
            192.168.20.17:

