all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      children:
        iw:
          archlinux:
          archarm:

        archlinux:
          children:
            arch:
              hosts:
                192.168.32.100:
                192.168.32.60:
                192.168.32.90:
                192.168.32.91:
                192.168.32.92:
            archarm:
              hosts:
                192.168.32.30:
                192.168.32.31:

        lxc:
          hosts:
            192.168.32.100:
            192.168.32.60:

        vm:
          hosts:
            192.168.32.90:
            192.168.32.91:
            192.168.32.92:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
              192.168.32.91:
              192.168.32.92:
            kubernetes_master:
              192.168.32.90:

        bastion:
          hosts:
            192.168.32.60:

        docker:
          hosts:

        grafana:
          hosts:
            192.168.32.30:

        jenkins:
          hosts:
            192.168.32.31:

        dns:
          hosts:
            192.168.32.100:

        proxmox:
          hosts:
            192.168.32.50:

