all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      children:
        iw:
          archlinux:
          archarm:

        archlinux:
          children:
            arch:
              hosts:
                192.168.64.90:
                192.168.64.91:
                192.168.64.92:
            archarm:
              hosts:

        vm:
          hosts:
            192.168.64.90:
            192.168.64.91:
            192.168.64.92:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
              hosts:
                192.168.64.91:
                192.168.64.92:
            kubernetes_master:
              hosts:
                192.168.64.90:

