all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        archlinux:
          children:
            arch:
              hosts:
                192.168.32.100:
                192.168.32.60:
            archarm:
              hosts:

        lxc:
          hosts:
            192.168.32.100:
            192.168.32.60:

        bastion:
          hosts:
            192.168.32.60:

        dns:
          hosts:
            192.168.32.100:

        proxmox:
          hosts:
            192.168.32.50:

