---
monitoring_packages:
  - name: prometheus
  - name: prometheus-node-exporter

kubernetes_packages:
  - name: containerd
  - name: crictl
  - name: kubeadm
  - name: kubelet
  - name: kubectl
  - name: cni-plugins
  - name: socat
  - name: ethtool
  - name: iptables-nft
  - name: conntrack-tools
  - name: argocd

kubernetes_master_packages:
  - name: helm
  - name: kustomize

servers:
  - name: tkpve-kube-cp01
    address: "192.168.30.90"
  - name: tkpve-kube-cp02
    address: "192.168.30.91"
  - name: tkpve-kube-nd01
    address: "192.168.30.92"
  - name: iwpve-kube-cp01
    address: "192.168.32.90"
  - name: iwpve-kube-nd01
    address: "192.168.32.91"
  - name: iwpve-kube-nd02
    address: "192.168.32.92"

master_servers:
  - name: tkpve-kube-cp01
    address: "192.168.30.90"
  - name: tkpve-kube-cp02
    address: "192.168.30.91"
  - name: iwpve-kube-cp01
    address: "192.168.32.90"

