---
site01:
  - name: grafana01
    address: 192.168.30.20
  - name: jenkins01
    address: 192.168.30.21
  - name: worker01
    address: 192.168.30.16
  - name: pihole01
    address: 192.168.30.3

site02:
  - name: grafana01
    address: 192.168.32.30
  - name: jenkins01
    address: 192.168.32.31
  - name: pihole01
    address: 192.168.32.100

